### ISSUE TITLE
Rewrite the extension in React.js

### ISSUE THREAD

**Issue by diananova** [GenderMagProject/GenderMagRecordersAssistant#108]
* **Feature description** 
Hi!  I recently started developing this extension in react.js. I've been working on it for just a couple of days and I think it's coming along nicely. React.js would allow to fix a lot of existing bugs as well as easily add new features. 

* **Code**
You can download the zip here: https://github.com/diananova/genderMagReact (instructions are in the readme file). Let me know what you think!

* **Quick demo**
https://vimeo.com/448721573

**Comment by roseg31** [comment]
Discussed offline: Tool will be staying in JS for maintainability since newcomers would need to know/learn react
