### ISSUE TITLE
Pre-fill text boxes

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#113]
* **Feature description:** (Example: Add an exit button)

When a user hits the back button we should always be showing them the text that they just inputted (prefilled) in the boxes.

* **Reason for the feature or improvement:** (Example: there is no right way to exit from the application)

Want to make sure that users don't have to retype their info and can see what they wrote

* **How does your idea fit with the aim/scope of the project?** (Example: feature gives the workflow) 

Makes use easier

* **What are the merits of the feature?** (Example: prevent data loss)

Ease of use, expected behavior for text boxes/back function

* **Screenshots, if you can show something similar, or a sketch:**
For example, when editing the pronouns for the persona (see below)
![Screenshot 2021-01-04 155204](https://user-images.githubusercontent.com/20049970/103591371-d16b3800-4ea4-11eb-8b2e-b5ef9ca73412.jpg)

* **Any other information:**

**Comment by subuash** [comment]
Fixed in Pull Request: #121
