### ISSUE TITLE
Fix back button saving on screenshot drawing

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#114]
* **What Operating System?**
Windows (applicable to all)
* **What version of Chrome?**

* **What version of Recorder's Assistant (GitHub version or Chrome Store version)?**
Github
* **What steps will reproduce the issue?**
Run normal session through to screenshot page
Click draw on image
Draw something
Click back arrow
Drawing was saved
* **What would you expect to be the outcome?**
The drawing should not be saved since there's a separate save button but no way to discard drawing
* **Any additional details/screenshots to help people to fix any potential bugs?**
![Screenshot 2021-01-04 155603](https://user-images.githubusercontent.com/20049970/103591564-5f472300-4ea5-11eb-9452-4c2a15e30726.jpg)

**Comment by PieCoder** [comment]
Closed in Pull Request #120
