### ISSUE TITLE
Continue button formatting broken

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#115]
* **What Operating System?**
Windows
* **What version of Chrome?**
Version 87.0.4280.88
* **What version of Recorder's Assistant (GitHub version or Chrome Store version)?**
Github
* **What steps will reproduce the issue?**
Run normal session, entering a longer action name (e.g. 'A longer subgoal name or something') until pop up window opens with action questions
Continue button is below the topbar it's supposed to be in
* **What would you expect to be the outcome?**
Continue button should not be pushed out of top bar
* **Any additional details/screenshots to help people to fix any potential bugs?**
Length of the action title is causing the button to be overflowing. Action title should not be continued in the topbar but should be in the main window.
Screenshot:
![Screenshot 2021-01-04 160327](https://user-images.githubusercontent.com/20049970/103591948-6de20a00-4ea6-11eb-8183-5118df97abde.jpg)

**Comment by PieCoder** [comment]
Closed in Pull Request #120
