### ISSUE TITLE
Conjugations Based on Pronoun

### ISSUE THREAD

**Issue by mayacdsouza** [GenderMagProject/GenderMagRecordersAssistant#138]
* **What Operating System?** 
    * Windows

* **What version of Chrome?** 
    * 113.0.5672.127 (Official Build) (64-bit) (cohort: Stable) 

* **What version of Recorder's Assistant (GitHub version or Chrome Store version)?** 
    * Chrome Store

* **What steps will reproduce the issue?** 
    * Choosing different pronouns to look at how the conjugations stay consistent.

* **What would you expect to be the outcome?** 
    * Conjugations should be based on the pronouns selected (I.e. they have vs. she has) and capitalizations in descriptions should be based on sentence placement.

* **Any additional details/screenshots to help people to fix any potential bugs?**
    
![image](https://github.com/GenderMagProject/GenderMagRecordersAssistant/assets/97061012/3157e948-b9b9-4e5c-8ae2-20fc04644965)

**Comment by JessA-L** [comment]
I have not been able to replicate this bug, but it may have been fixed since this report was opened.

**Comment by roseg31** [comment]
Unable to replicate. Closing issue.
