### ISSUE TITLE
Broken YouTube Link

### ISSUE THREAD

**Issue by daledanica** [GenderMagProject/GenderMagRecordersAssistant#146]
* MacOS - Venture 13.6

* Brave 1.60.110 (runs the most recent version of Chrome)

* The issue is with the most recent version of the README (Dec. 11, 2023)

* On any browser, if you click the YouTube link under "How to install the GenderMag Recorder's Assistant, Method 1: Download from GitHub," labeled as "Tutorial for download on Mac," it will launch YouTube, but YouTube gives the message that "This video isn't available anymore" (see attached screenshot).

* One would expect there to be an available video to watch, perhaps it has been made private.

* <img width="512" alt="YouTube Unavailable Video Notification" src="https://github.com/GenderMagProject/GenderMagRecordersAssistant/assets/97426718/8c4e825f-0155-43ee-b572-ff7194778382">

**Comment by roseg31** [comment]
Resolved
