### ISSUE TITLE
Tool doesn't work with background javascript/audio

### ISSUE THREAD

**Issue by hyjiang7** [GenderMagProject/GenderMagRecordersAssistant#40]
* **What Operating System?**
MacOS Mojave
* **What steps will reproduce the issue?**
Problem: After performing action and recording facets, clicking on "Save and Continue" button does not result in saving and continuing on with the session.  
Start a new GenderMag session on any website. Choose any persona besides Abby. Follow through the instructions. After performing the action for the your subgoal, click on continue. Then record your facets and click on "Save and Continue" button. Button will not perform any actions. 
* **What would you expect to be the outcome?**
The "Save and Continue" button should allow your facets to be saved. I should be allowed to enter in more actions/subgoals or exit out of program. 
* **All these details will help people to fix any potential bugs?**
I noticed that the problem arises for non-Abby personas. In addition, you may have to go through several actions/subgoals before problem arises. 

![gendermag-session](https://user-images.githubusercontent.com/34972371/58606554-cd9b1c80-8250-11e9-8855-ef4a94a8e296.gif)

**Comment by Brijbhuva** [comment]
Hello @hyjiang7 

I think it seems to be website specific issue can you let me know on which web page you are facing this issue while using the GenderMag Tool?

**Comment by hyjiang7** [comment]
Hi @Brijbhuva 

I tried a few websites and I all encountered the same problem. The ones I remember off the top of my head were Disneyland's official website and yahoo page.

**Comment by Brijbhuva** [comment]
This is the known issue javascript of the extension is not working properly when we have any audio or video animation javascript running on the testing website in the background.
