### ISSUE TITLE
File Download is Required

### ISSUE THREAD

**Issue by sairaja9** [GenderMagProject/GenderMagRecordersAssistant#66]
* **What Operating System?**
Windows 10

![image](https://user-images.githubusercontent.com/41133449/60738341-e0210980-9f12-11e9-9d33-13034583df59.png)

* **What steps will reproduce the issue?**
As shown in the screenshot above, the zip file containing session information is downloaded automatically when the save and exit button is clicked.  If a user is not satisfied with a session, they may not want to download a zip file.  This may result in an annoyed user.

* **What would you expect to be the outcome?**
A user would expect an "exit without download" button after clicking exit.

* **All these details will help people to fix any potential bugs?**
By adding such a button below the Re-Download Zip File button, the user will understand that they can delete or save the session's information.  This bug can also be fixed if there is a separate exit button apart from the save and exit button.

**Comment by anizhou** [comment]
Hello, I've been working on this issue. Please expect a pull request some time in the near future. Thank you.
