### ISSUE TITLE
Add Style Guide to Contributing Guildines

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#77]
Contributing guidelines should include or link to a style guide so that all contributors can help keep the code understandable and maintainable. 

Some ideas for guidelines include: 
- Keeping code line length at 80 chars or less
- Adding comments for all functions
- Commenting or flagging issues when broken code is found
- Naming conventions (e.g. camel case for function names and file names)
- Writing descriptive commit messages/pull requests

**Comment by roseg31** [comment]
Additional information:  https://google.github.io/styleguide/jsguide.html

**Comment by PieCoder** [comment]
Committed at 939c7df
