### ISSUE TITLE
Verify GitHub download instructions

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#85]
The instructions on how to download from GitHub in the README need to be tested and verified. A couple of people with no experience downloading this tool should attempt to follow the instructions given and if there is any additional information or confusion at all, the instructions should be updated accordingly.

**Comment by roseg31** [comment]
Also if updates are made, please update the identical instructions in Contributing.md

**Comment by caroline-g** [comment]
I don't have previous experience with GitHub/downloading GenderMag and was able to download the extension to Chrome on my Windows based on the current guidelines pretty seamlessly/quickly. A few possible points of confusion:

- Step 3: When I first downloaded the zip file, right-clicking on the file doesn't pull up "Extract All" (the 1st file you land on is master file folder, not the zip master folder)
     -"Extract All" shows up at _top_ of files tab bar 
     - Have to navigate backward to "Downloads" before you're able see zip file & and right-click + "Extract All"

-Step 7: "Load Unpacked extension" shows up as "load unpacked" in my browser (minor issue, may differ by browser version)

-Step 8: Clarify that you have to select extracted _zip_ file (not just the file folder, which has the same name as the zip folder & creates error message when you try to upload it)

**Comment by emlabor** [comment]
It seems these instructions are slightly specific to Windows. I can add Mac instructions in the next few days.
