### ISSUE TITLE
Errors happened when click on the small icon at the right of the address bar on Chrome

### ISSUE THREAD

**Issue by li-xiaoying** [GenderMagProject/GenderMagRecordersAssistant#87]
* **What Operating System?**
Windows 10 Eduation

* **What steps will reproduce the issue?**
1. Install the GenderMag Recorder's Assistant by downloading it from GitHub.
2. A small icon of it appeared at the right of the address bar. Click on it, and an “Errors” button appeared.
![image](https://user-images.githubusercontent.com/59781881/84232701-b3bc2880-aaa5-11ea-9141-76cc47d22af5.png)
3. Click on the “Errors” button, and it showed the following errors:
![image](https://user-images.githubusercontent.com/59781881/84232766-d8b09b80-aaa5-11ea-8600-10740a8a5103.png)

* **What would you expect to be the outcome?**
Clicking on the small icon will lead users to the homepage of GenderMag Recorder's Assistant, and no errors would show up.

* **All these details will help people to fix any potential bugs?**
It seems the feature corresponding to the small icon was omitted during the development process. Since the icon appears directly after users install the GenderMag Recorder's Assistant, and users are likely to click the icon, its feature should be fullfilled.

**Comment by roseg31** [comment]
Temporary fix in 93204f8
