### ISSUE TITLE
Intro page 'click here' link can be confusing

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#91]
The intro page says "to learn more about GenderMag, click here"

This may confuse Abi and they might want to click there instead of starting the session so it needs to be reworded or maybe there can be a tooltip available on the text "The GenderMag Method" (see below)
![newlinkintro](https://user-images.githubusercontent.com/20049970/84928676-a98cc200-b083-11ea-91a4-33f452895b70.jpg)
example tooltip:
![exptooltip](https://user-images.githubusercontent.com/20049970/84928818-da6cf700-b083-11ea-8e0e-15076ee9f11b.jpg)

**Comment by emlabor** [comment]
I've rephrased to "More information about GenderMag can be found on our [website](http://gendermag.org/)."
