### ISSUE TITLE
Remove redundant text in introduction

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#92]
The team field page and the persona selection pages all have this text: "Before you get started with the GenderMag walkthrough, please enter some information that will help identify this session."

It is confusing to see this text multiple times and the user might think they are not making progress or may get confused. This text should disappear and there should be a different indicator that this is the pre-session form

![teampage](https://user-images.githubusercontent.com/20049970/84929465-b3fb8b80-b084-11ea-8816-2900d29c6c5b.jpg)
![personapage](https://user-images.githubusercontent.com/20049970/84929476-b5c54f00-b084-11ea-9cf1-4625fea7a658.jpg)
![personapage2](https://user-images.githubusercontent.com/20049970/84929484-b8c03f80-b084-11ea-9c12-1c8f77c6ceb3.jpg)

**Comment by emlabor** [comment]
Added text at the top indicating whether GenderMag is "In Session" or "Pre-Session Setup".
