### ISSUE TITLE
Explain what a 'gendermag session' is

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#93]
The documentation and the tool itself use the phrase "GenderMag session" but it is not defined for the user so it can cause confusion. This needs to be defined in the main documentation and in the intro section of the tool. The intro section of the tool also uses the phrase "GenderMag walkthrough" and this should be replaced with "GenderMag session" for consistency.

(A GenderMag session is just an instance of using the GenderMag method so by filling out the fields in the tool you are completing a GenderMag session)

![gmsessiondoc](https://user-images.githubusercontent.com/20049970/84930130-ac88b200-b085-11ea-83c1-3a5da4d6c3e4.jpg)
![gmsessiontool](https://user-images.githubusercontent.com/20049970/84930136-af83a280-b085-11ea-86fd-90b400bb276c.jpg)

**Comment by emlabor** [comment]
Working on this.
