### ISSUE TITLE
Convert distributed setting guide to MD file

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#94]
The distributed setting file ([here](https://github.com/mendezc1/GenderMagRecordersAssistant/blob/master/HOW%20TO%20Use%20the%20Tool%20REMOTELY%20for%20DISTRIBUTED%20teams.docx)) needs to be converted into its own appropriately formatted .md file. This content can stay the same. The docx file should be deleted from the repo once the md file is complete.

**Comment by burnettm** [comment]
Issue #98 depends on this issue.

**Comment by diananova** [comment]
I'm working on it. Should be done by the end of the week. (Rewrite Your Summer Program)

**Comment by diananova** [comment]
Done!

**Comment by roseg31** [comment]
Closed in #103
