### ISSUE TITLE
Update team name field

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#95]
The team name field may be confusing considering that one person may be using the tool instead of a team. The text should be updated to reflect that so the users are not confused. There is also currently no explanation of what the team name is or what 'team' it is referencing so adding some clarification would be good.
![teamname](https://user-images.githubusercontent.com/20049970/84933137-45b9c780-b08a-11ea-9da4-356147a48a0a.jpg)

**Comment by emlabor** [comment]
Working on this.
