### ISSUE TITLE
Add detailed instructions on screenshot/highlight

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#96]
The instructions on the page before the screenshot takes place are not very detailed. The user needs to be able to read them and know exactly what to do to take the screenshot. Additionally, they need to know the tool window will temporarily close so they are not worried they did something wrong. 

![badinstructions](https://user-images.githubusercontent.com/20049970/84933603-017af700-b08b-11ea-8e4f-a9ea4b44cac9.jpg)

**Comment by emlabor** [comment]
Working on this.
