### ISSUE TITLE
Update text for adding action and subgoal to improve clarity

### ISSUE THREAD

**Issue by roseg31** [GenderMagProject/GenderMagRecordersAssistant#97]
The button text for the add subgoal and add action fields should be updated to say "add this subgoal" and "add this action" or something similar like "save", "enter", etc, b/c "add subgoal" and "add action" may imply that the button will generate another field or have different behavior.

![subgoalinstr](https://user-images.githubusercontent.com/20049970/84934126-c0371700-b08b-11ea-9a9e-c62655278c67.jpg)
![actioninstr](https://user-images.githubusercontent.com/20049970/84934137-c4fbcb00-b08b-11ea-83a1-91d98d3401d7.jpg)

**Comment by emlabor** [comment]
I'll work on this.
